version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Seoul"
    labels:
      - "actions-dependencies"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Seoul"
    labels:
      - "gomod-dependencies"
