{
 "title": "Squid Dashboard",
 "tags": [
  "kubernetes",
  "squid",
  "proxy"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "## Squid Dashboard by [squid-exporter](https://github.com/boynux/squid-exporter/tree/master)\n\nSquid Proxy Server dashboards (Successor of dynamic proxy)\n\n![Squid](https://www.squid-cache.org/Images/img4.jpg)"
   }
  },
  {
   "title": "Services Up",
   "type": "stat",
   "description": "Was the last query of squid successful?",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "squid_up{host=\"localhost\"}",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Bytes Hit Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "squid_client_http_hit_kbytes_out_bytes_total / squid_client_http_kbytes_out_kbytes_total"
    }
   ]
  },
  {
   "title": "Catch Hit Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "squid_client_http_hits_total / squid_client_http_requests_total",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Reqeust failure ratio (Average)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(squid_info_Request_failure_ratio)",
     "legendFormat": "Request failure ratio"
    }
   ]
  },
  {
   "title": "Squid CPU Usage (Average for 5m)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "squid_info_CPU_Usage_5_minute_avg * 100",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Squid CPU Usage (Average for 60m)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "squid_info_CPU_Usage_60_minute_avg * 100",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(squid_client_http_requests_total[5m])",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "rate(squid_client_http_hits_total[5m])",
     "legendFormat": "Total HTTP hits"
    },
    {
     "expr": "rate(squid_client_http_errors_total[5m])",
     "legendFormat": "Total Errors"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(squid_client_http_kbytes_in_kbytes_total[5m]) * -1",
     "legendFormat": "HTTP Traffic in"
    },
    {
     "expr": "rate(squid_client_http_kbytes_out_kbytes_total[5m])",
     "legendFormat": "HTTP Traffic Out"
    },
    {
     "expr": "rate(squid_client_http_hit_kbytes_out_bytes_total[5m])",
     "legendFormat": "HTTP Traffic Out Hits"
    }
   ]
  },
  {
   "title": "Client Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(squid_client_http_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Errors Rate (All)",
   "type": "timeseries",
   "description": "The total number of proxy server all errors (Range)",
   "gridPos": { "h": 12, "w": 5, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(squid_server_all_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Open File Discriptors (Average)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(process_open_fds{app_kubernetes_io_name=\"squid\"}[5m])",
     "legendFormat": "Open File Descriptor"
    },
    {
     "expr": "avg_over_time(squid_info_Available_number_of_file_descriptors{app_kubernetes_io_name=\"squid\"}[5m])",
     "legendFormat": "Available File Descriptor"
    }
   ]
  }
 ]
}