{{/*
Expand the name of the chart.
*/}}
{{- define "name" -}}
{{- default $.Chart.Name $.Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create chart name by the chart label.
*/}}
{{- define "chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Return labels, including name and globalLabels 
*/}}
{{- define "labels" -}}
helm.sh/chart: {{ include "chart" . | quote }}
{{- if .globalLabels }}
{{ toYaml .globalLabels }}
{{- end -}}
{{- end -}}

{{/*
Return NodePool labels.
*/}}
{{- define "nodePool.labels" -}}
{{ include "labels" . | indent 8}}
{{- if .labels }}
{{ toYaml .labels | indent 8 }}
{{- end -}}
{{- end -}}

{{/*
Common selector terms helper for subnet, security group, and AMI selectors
*/}}
{{- define "ec2NodeClass.commonSelectorTerms" -}}
{{- range . }}
  {{- with .tags }}
  - tags:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .id }}
  - id: {{ . }}
  {{- end }}
  {{- with .name }}
  - name: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}