{{/*
nodepool custom resource template (compatible with karpenter v1.3.0)
*/}}

{{- range $key, $value := .Values.nodePool }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ $key }}
spec:
  template:
    metadata:
      labels:
        {{ template "nodePool.labels" (dict "labels" .labels "Release" $.Release "Chart" $.Chart "globalLabels" $.Values.globalLabels) }}  
      annotations:
        {{- with (merge .annotations $.Values.globalAnnotations) }}
        {{ toYaml . }}
        {{- end }}
    spec:
      {{- with .nodeClassRef }}
      nodeClassRef:
        group: {{ default "karpenter.k8s.aws" .group }}
        kind: {{ default "EC2NodeClass" .kind }}
        name: {{ default "default" .name }}
      {{- end }}
      taints:
        {{- with .taints }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      startupTaints:
        {{- with .startupTaints }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      expireAfter: {{ default "720h" .expireAfter }}
      requirements:
        {{- with .requirements }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      kubelet:
        {{- with .kubelet }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

  {{- if .disruption }}
  {{- with .disruption }}
  disruption: 
    consolidationPolicy: {{ default "WhenEmptyOrUnderutilized" .consolidationPolicy }}
    consolidateAfter: {{ .consolidateAfter }}
    {{- with .budgets }}
    budgets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- end }}

  {{- if .limits }}
  limits:
    cpu: {{ default 100 .limits.cpu }}
    memory: {{ default "100Gi" .limits.memory }}
  {{- end }}
  
  {{- if .weight }}
  weight: {{ .weight }}
  {{- end }}
{{- end }}
